export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const START_ADD_MAP = 'START_ADD_MAP';
export const END_ADD_MAP = 'END_ADD_MAP';
export const SAVE_NEW_MAP = 'SAVE_NEW_MAP';

export const START_ADD_FRAME = 'START_ADD_FRAME';
export const END_ADD_FRAME = 'END_ADD_FRAME';
export const SAVE_NEW_FRAME = 'SAVE_NEW_FRAME';

export const LOAD_MAP_LIST = 'LOAD_MAP_LIST';
export const MAP_LIST_REQUEST = 'MAP_LIST_REQUEST';
export const MAP_LIST_RECEIVE = 'MAP_LIST_RECEIVE';
export const MAP_LIST_ERROR = 'MAP_LIST_ERROR';

export const MAP_OPTIONS_OPEN = 'MAP_OPTIONS_OPEN';
export const MAP_OPTIONS_CLOSED = 'MAP_OPTIONS_CLOSED';
